import type { NextPage } from 'next'
import Head from 'next/head'
import getPlus from './components/GetPlus'
import styles from '../styles/About.module.scss'
import Link from 'next/link'

const About: NextPage = () => {
  return (
    <div className={`page ${styles.about}`}>
      <Head>
        <title>About - MDervent</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.plus_list}>
        {getPlus({count:120})}
      </div>
      <div className={styles.page_desc}>
        <h1>ABOUT</h1>
        <h2>Sr.FrontEnd Developer</h2>
        </div>
        <div className={styles.page_content}>
          <div className={styles.content}>
            <p>I use HTML & CSS (usually SASS) every day, and I try to keep up with the latest features while maintaining graceful degradation.</p>
            <p>I use JavaScript fairly often, usually with jQuery. I also run Node.js-based workflow automation via Gulp or Grunt for web projects, and I’ve written other Node scripts to automate mundane tasks.</p>
            <p>My main server-side language is PHP, quite often paired with MySQL.</p>
            <Link href='/my-resume'>
              <a className='btn btn-border'>My Resume</a>
            </Link>
          </div>
        </div>
    </div>
  )
}

export default About
