import type { NextPage } from 'next'
import Head from 'next/head'
import getPlus from './components/GetPlus'
import styles from '../styles/Contact.module.scss'

const Contact: NextPage = () => {
  return (
    <div className={`page ${styles.contact}`}>
      <Head>
        <title>Contact - MDervent</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.plus_list}>
        {getPlus({count:120})}
      </div>
      <div className={styles.page_desc}>
        <h1>CONTACT</h1>
        <h2>WRITE TO ME</h2>
        </div>
        <div className={styles.page_content}>
        <div className={styles.content}>
            <h2>CONTACT US</h2>
            <h3>Telephone</h3>
            <p><a href="tel:05325524426">+90 532 552 44 26</a></p>
            <h3>E-Mail</h3>
            <p><a href="mailto:hi@mdervent.com">hi@mdervent.com</a></p>
            <h3>Location</h3>
            <p>ISTANUL/TURKIYE</p>
        </div>
        </div>
    </div>
  )
}

export default Contact
