import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import getPlus from './components/GetPlus';
import styles from '../styles/Works.module.scss';
import { Navigation, Pagination, EffectCreative, A11y } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css/pagination';
import 'swiper/css';
import 'swiper/css/effect-creative';
import React from 'react';

const Works: NextPage = () => {
  const [activeSlide, setActiveSlide] = React.useState(0);
  const navigationPrevRef = React.useRef(null);
  const navigationNextRef = React.useRef(null);
  const workList = [
    {
      title: 'PLAXY',
      type: 'NFT',
      brand: 0,
      year: '2022',
      image: '/works/plaxy.jpg',
    },
    {
      title: 'NATURIA KEMER',
      type: 'SALES PROMOTIONS',
      brand: 0,
      year: '2022',
      image: '/works/naturia-kemer.jpg',
    },
    {
      title: 'PUCK GLOBAL',
      type: 'AGENCY CORPORATE',
      brand: 0,
      year: '2021',
      image: '/works/puck-global.jpg',
    },
    {
      title: 'LENORE MIMARLIK',
      type: 'CORPORATE',
      brand: 0,
      year: '2021',
      image: '/works/lenore-mimarlik.jpg',
    },
    {
      title: 'TUHA ELEKTRIK',
      type: 'CORPORATE',
      brand: 0,
      year: '2021',
      image: '/works/tuha-elektrik.jpg',
    },
    {
      title: 'BOBO SCOPE',
      type: 'MAGAZINE',
      brand: 0,
      year: '2020',
      image: '/works/bobo-scope.jpg',
    },
    {
      title: 'TARGET',
      type: 'CORPORATE',
      brand: 0,
      year: '2018',
      image: '/works/target.jpg',
    },
    {
      title: 'MACFIT',
      type: 'CORPORATE',
      brand: 1,
      year: '2018',
      image: '/works/macfit.jpg',
    },
    {
      title: 'HAYAT SU',
      type: 'E-COMMERCE',
      brand: 1,
      year: '2018',
      image: '/works/hayat-su.jpg',
    },
    {
      title: 'TAVUK DUNYASI',
      type: 'CORPORATE',
      brand: 1,
      year: '2018',
      image: '/works/tavuk-dunyasi.jpg',
    },
    {
      title: 'FLYPGS',
      type: 'CORPORATE',
      brand: 1,
      year: '2017',
      image: '/works/flypgs.jpg',
    },
    {
      title: 'CINEMAXIMUM',
      type: 'CORPORATE',
      brand: 1,
      year: '2017',
      image: '/works/cinemaximum.jpg',
    },
    {
      title: 'DANONE PRO+',
      type: 'PRODUCT PROMOTION',
      brand: 1,
      year: '2017',
      image: '/works/danone-proplus.jpg',
    },
    {
      title: 'YAPI KREDI FAKTORING',
      type: 'CORPORATE',
      brand: 1,
      year: '2017',
      image: '/works/yapikredi-faktoring.jpg',
    },
    {
      title: 'PEUGEOT 2.EL',
      type: 'CORPORATE',
      brand: 1,
      year: '2017',
      image: 'https://picsum.photos/id/4/540/640',
    },
    {
      title: 'KAYA PEYZAJ',
      type: 'CORPORATE',
      brand: 1,
      year: '2017',
      image: '/works/kaya-peyzaj.jpg',
    },
  ];
  const brands = [
    {
      title: 'FREELANCE',
    },
    {
      title: 'Nexum Creative',
    },
    {
      title: '-99 Design Studio',
    },
  ];
  const getWorkList = () => {
    let works = [];
    let index = 0;
    for (let work of workList) {
      index++;
      works.push(
        <SwiperSlide key={index} className={styles.workSwiperSlide}>
          <figure className={styles.workItemFigure}>
            <img src={work.image} className={styles.workItemFigureImage} />
          </figure>
          <div className={styles.workItemTextWrap}>
            <span
              className={styles.workItemTextYear}
              data-swiper-parallax="-100"
            >
              {work.year}
            </span>
            <span
              className={styles.workItemTextType}
              data-swiper-parallax="-300"
            >
              {work.type}
            </span>
          </div>
        </SwiperSlide>
      );
    }
    return works;
  };
  return (
    <div className={`page ${styles.works}`}>
      <Head>
        <title>Works - MDervent</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.plus_list}>{getPlus({ count: 120 })}</div>
      <div className={styles.page_desc}>
        <div className={styles.page_text}>
          <h1>{workList[activeSlide].title}</h1>
          <h2>{brands[workList[activeSlide].brand].title}</h2>
        </div>
        <div className={styles.page_detail}>
          <div className={styles.workItemTextYear}>
            {workList[activeSlide].year}
          </div>
          <div className={styles.workItemTextType}>
            {workList[activeSlide].type}
          </div>
        </div>
        <div className={styles.slideNavigation}>
          <div className={styles.slideNavigationPrev} ref={navigationPrevRef}>
            PREV
          </div>
          <div className={styles.slidePagination}>
            <span className={styles.slidePaginationCurrent}>
              {activeSlide + 1}
            </span>
            <span className={styles.swiperPaginationSeperator}>/</span>
            <span className={styles.swiperPaginationTotal}>
              {workList.length}
            </span>
          </div>
          <div className={styles.slideNavigationNext} ref={navigationNextRef}>
            NEXT
          </div>
        </div>
      </div>
      <div className={styles.page_content}>
        <div className={styles.content}>
          <Swiper
            modules={[Navigation, Pagination, EffectCreative, A11y]}
            effect="creative"
            grabCursor={true}
            parallax={true}
            pagination={{ clickable: true }}
            spaceBetween={0}
            creativeEffect={{
              prev: {
                shadow: true,
                translate: [0, 0, -400],
              },
              next: {
                translate: ['100%', 0, 0],
              },
            }}
            slidesPerView={1}
            className={styles.swiper}
            navigation={{
              prevEl: navigationPrevRef.current,
              nextEl: navigationNextRef.current,
            }}
            onSlideChange={(swiper) => {
              setActiveSlide(swiper.activeIndex);
            }}
            onInit={(swiper) => {
              setTimeout(() => {
                // @ts-ignore
                swiper.params.navigation.prevEl = navigationPrevRef.current;
                // @ts-ignore
                swiper.params.navigation.nextEl = navigationNextRef.current;
                swiper.navigation.destroy();
                swiper.navigation.init();
                swiper.navigation.update();
              });
            }}
          >
            {getWorkList()}
          </Swiper>
        </div>
      </div>
    </div>
  );
};

export default Works;
